version: '3'
services:
  mock:
    container_name: "mock"
    image: node:alpine
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./mock:/app